# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b2e071a207be41b383d34a8d9f8a0ec8ef91a179fe0d3933cdefd9707bdecab75df81e87dba631ba4505641b53bfc699ce76b0c5b0d36873ce0ffb4684d0b0e

test:
  secret_key_base: 43242a6ab0983683e8e6cf84b9a2b080402d78bffcf0f43e4fe7ab1760d05fbf22abd742de013c224c43a3de9eb72acc762e1e99ee77e2f9f5d702371146628a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
